github:
  description: "Slack Chat Archiver"
notifications:
  commits: commits@fineract.apache.org
  pullrequests: issues@fineract.apache.org
github:
  enabled_merge_buttons:
    merge: true
    squash: false
    rebase: false
  protected_branches:
    main:
      required_linear_history: false
      required_signatures: true
      required_conversation_resolution: true
